rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_1_1 >> result_p_1_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_1_1 >> result_p_1_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_1_1 >> result_p_1_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_2_1 >> result_p_2_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_2_1 >> result_p_2_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_2_1 >> result_p_2_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_4_1 >> result_p_4_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_4_1 >> result_p_4_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
./linkedlist_p_4_1 >> result_p_4_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_1_1 >> result_1_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_1_1 >> result_1_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_1_1 >> result_1_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_2_1 >> result_2_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_2_1 >> result_2_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_2_1 >> result_2_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_4_1 >> result_4_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_4_1 >> result_4_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
./linkedlist_4_1 >> result_4_1_del.txt
rm -f /mnt/ext4-pmem22/persistent_apps/linkedlist_p.txt
