rm -f /mnt/ext4-pmem22/persistent_apps/b+tree_new_*.txt
./b+tree_intel_1_1 >> result_b+tree_1_1.txt
rm -f /mnt/ext4-pmem22/persistent_apps/b+tree_new_*.txt
./b+tree_intel_2_1 >> result_b+tree_2_1.txt
rm -f /mnt/ext4-pmem22/persistent_apps/b+tree_new_*.txt
./b+tree_intel_4_1 >> result_b+tree_4_1.txt
rm -f /mnt/ext4-pmem22/persistent_apps/b+tree_new_*.txt
./b+tree_intel_p_1_1 >> result_b+tree_p_1_1.txt
rm -f /mnt/ext4-pmem22/persistent_apps/b+tree_new_*.txt
./b+tree_intel_p_2_1 >> result_b+tree_p_2_1.txt
rm -f /mnt/ext4-pmem22/persistent_apps/b+tree_new_*.txt
./b+tree_intel_p_4_1 >> result_b+tree_p_4_1.txt
